services:
  backend:
    container_name: backend-dev
    build:
      context: .
      dockerfile: Backend/Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./Backend:/app/Backend
      - ./Application:/app/Application
      - ./Domain:/app/Domain
      - ./Infrastructure:/app/Infrastructure
      - ./Shared:/app/Shared
      - nuget_cache:/root/.nuget/packages

      - backend_backend_obj:/app/Backend/obj
      - backend_backend_bin:/app/Backend/bin
      - backend_application_obj:/app/Application/obj
      - backend_application_bin:/app/Application/bin
      - backend_domain_obj:/app/Domain/obj
      - backend_domain_bin:/app/Domain/bin
      - backend_infrastructure_obj:/app/Infrastructure/obj
      - backend_infrastructure_bin:/app/Infrastructure/bin
      - backend_shared_obj:/app/Shared/obj
      - backend_shared_bin:/app/Shared/bin
    working_dir: /app/Backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=true
    command: dotnet watch run --non-interactive --no-launch-profile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/swagger"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  frontend:
    container_name: frontend-dev
    build:
      context: .
      dockerfile: Frontend/Dockerfile.dev
    ports:
      - "5100:5000"
    volumes:
      - ./Frontend:/app/Frontend
      - ./Application:/app/Application
      - ./Domain:/app/Domain
      - ./Shared:/app/Shared
      - nuget_cache:/root/.nuget/packages

      - frontend_frontend_obj:/app/Frontend/obj
      - frontend_frontend_bin:/app/Frontend/bin
      - frontend_application_obj:/app/Application/obj
      - frontend_application_bin:/app/Application/bin
      - frontend_domain_obj:/app/Domain/obj
      - frontend_domain_bin:/app/Domain/bin
      - frontend_shared_obj:/app/Shared/obj
      - frontend_shared_bin:/app/Shared/bin
    working_dir: /app/Frontend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=true
    command: dotnet watch run --non-interactive --no-launch-profile --no-hot-reload
    depends_on:
      backend:
        condition: service_healthy

volumes:
  nuget_cache:

  backend_backend_obj:
  backend_backend_bin:
  backend_application_obj:
  backend_application_bin:
  backend_domain_obj:
  backend_domain_bin:
  backend_infrastructure_obj:
  backend_infrastructure_bin:
  backend_shared_obj:
  backend_shared_bin:

  frontend_frontend_obj:
  frontend_frontend_bin:
  frontend_application_obj:
  frontend_application_bin:
  frontend_domain_obj:
  frontend_domain_bin:
  frontend_shared_obj:
  frontend_shared_bin: