services:
  backend-staging:
    image: myapp/backend-staging:${TAG:-latest}
    container_name: backend-staging
    build:
      context: .
      dockerfile: Backend/Dockerfile.staging
      args:
        DOTNET_VERSION: "8.0"
        BUILD_CONFIGURATION: Release
    ports:
      - "127.0.0.1:8180:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    restart: unless-stopped

  frontend-staging:
    image: myapp/frontend-staging:${TAG:-latest}
    container_name: frontend-staging
    build:
      context: .
      dockerfile: Frontend/Dockerfile.staging
      args:
        DOTNET_VERSION: "8.0"
        BUILD_CONFIGURATION: Release
    ports:
      - "127.0.0.1:5180:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    depends_on:  
         backend-staging:  
           condition: service_started  
    restart: unless-stopped
