//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frontend.Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Frontend.Resources.Pages.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience the simplicity and efficiency of Invoicer, where invoicing is just a few clicks away..
        /// </summary>
        public static string ClosingStatement {
            get {
                return ResourceManager.GetString("ClosingStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoicer transforms your accounting tasks into a breeze, offering:.
        /// </summary>
        public static string DescriptionIntro {
            get {
                return ResourceManager.GetString("DescriptionIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automated invoice generation.
        /// </summary>
        public static string FeatureAutomation {
            get {
                return ResourceManager.GetString("FeatureAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effortless client management.
        /// </summary>
        public static string FeatureClients {
            get {
                return ResourceManager.GetString("FeatureClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed, comprehensive reports.
        /// </summary>
        public static string FeatureReports {
            get {
                return ResourceManager.GetString("FeatureReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ultimate, easy-to-use invoicing solution..
        /// </summary>
        public static string WelcomeSubtitle {
            get {
                return ResourceManager.GetString("WelcomeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Invoicer.
        /// </summary>
        public static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
    }
}
